@echo off
title Starting Athena AI...
echo Activating Conda environment...
call conda activate llamaconda

echo Changing directory to Athena project...
cd /d "C:\Athena-Agent Hybrid AI"

echo Starting Athena AI...
python main.py

echo Athena AI has stopped.
pause
